import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";

import clsx from 'clsx'

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

export const metadata: Metadata = {
  title: "Jeandoe blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      className={clsx(inter.variable, manrope.variable, "font-mr bg-light dark:bg-dark")}
      >
        {children}
      </body>
    </html>
  );
}
